In [88]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score,precision_score,classification_report,f1_score,confusion_matrix
from sklearn.model_selection import train_test_split
import xgboost
from xgboost import XGBClassifier

In [89]:
textSpam=pd.read_csv("spam.csv",encoding="ISO-8859-1")
textSpam

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

In [90]:
textSpam=textSpam.drop(columns=['Unnamed: 2','Unnamed: 3','Unnamed: 4'])

In [91]:
textSpam

        v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [92]:
# reorder
textSpam=textSpam[['v2','v1']]

In [93]:
textSpam.columns=["Text","is_fraud"]

In [94]:
textSpam

                                                   Text is_fraud
0     Go until jurong point, crazy.. Available only ...      ham
1                         Ok lar... Joking wif u oni...      ham
2     Free entry in 2 a wkly comp to win FA Cup fina...     spam
3     U dun say so early hor... U c already then say...      ham
4     Nah I don't think he goes to usf, he lives aro...      ham
...                                                 ...      ...
5567  This is the 2nd time we have tried 2 contact u...     spam
5568              Will Ì_ b going to esplanade fr home?      ham
5569  Pity, * was in mood for that. So...any other s...      ham
5570  The guy did some bitching but I acted like i'd...      ham
5571                         Rofl. Its true to its name      ham

[5572 rows x 2 columns]

In [95]:
# cheeck null valuees
textSpam.isnull().sum()

Text        0
is_fraud    0
dtype: int64

In [96]:
# Label encoder
labelEncoder=LabelEncoder()

In [97]:
# split data
x=textSpam['Text']
y=textSpam['is_fraud']
xTrain,xTest,yTrain,yTest=train_test_split(x,y,test_size=0.25,random_state=34)

In [98]:
# Encode Ytrain
yTrain=labelEncoder.fit_transform(yTrain)

In [99]:
# encode ytest
yTest=labelEncoder.transform(yTest)

In [100]:
# VECTORIZING TEXT
vector= TfidfVectorizer(
    max_features=3000,
    ngram_range=(1, 2),
    stop_words='english'
)

In [101]:
 xTrain = vector.fit_transform(xTrain)

In [102]:
xTest  = vector.transform(xTest)

In [103]:
# model 
model = XGBClassifier(
    n_estimators=1000,
    learning_rate=0.1,
    reg_alpha=0.01,
    reg_lambda=0.01,
    random_state=42
)

model.fit(xTrain,yTrain)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=1000,
              n_jobs=None, num_parallel_tree=None, ...)

In [104]:
# prediction
featurePrediction=model.predict(xTest)

In [106]:
labelEncoder.classes_

array(['ham', 'spam'], dtype=object)

In [87]:
labelEncoder.classes_=[]

AttributeError: 'LabelEncoder' object has no attribute 'classes_'

In [75]:
# classification report
report=classification_report(yTest,featurePrediction,target_names =labelEncoder.classes_,output_dict=True)

In [76]:
# classification report Df
reportFrame=pd.DataFrame(report).transpose()
reportFrame

              precision    recall  f1-score      support
Not Fraud      0.974797  0.992550  0.983593  1208.000000
Fraud          0.944785  0.832432  0.885057   185.000000
accuracy       0.971285  0.971285  0.971285     0.971285
macro avg      0.959791  0.912491  0.934325  1393.000000
weighted avg   0.970811  0.971285  0.970507  1393.000000